import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { useState, useEffect, useRef } from 'react';
import { styled } from '@stitches/react';
import AppHeader from './components/AppHeader';
import ActionLayout from './components/ActionLayout';
import ScrapeQueue from './components/ScrapeQueue';
import TileChannel, {TileChannelProps} from './components/scrape/TileChannel';
import ScrapeForm from './components/scrape/ScrapeForm';
import Layout from './components/search/Layout';


// const Button = styled('button', {
//     backgroundColor: 'gainsboro',
//     borderRadius: '9999px',
//     padding: '10px 15px',
//     '&:hover': {
//         backgroundColor: 'lightgray',
//     },
// });

const Home: NextPage = () => {
    
    return (
        <div className="container is-fluid">
            <Head>
                <title>main app</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            
            <AppHeader key={"header"}/>
            <ScrapeForm key={"form"}/>
            <TileChannel  key={"test"} compact={false} />
            <Layout key="main" />
            
            <span className='breakFix'></span>
            <section className='container is-fluid'>
                <p className='primary-font'>the quick brown fox jumped over the lazy dog.</p>
                <p className='alt-font'>the quick brown fox jumped over the lazy dog.</p>
                <p className='alt-font2'>the quick brown fox jumped over the lazy dog.</p>
            </section>
            <span className='breakFix'></span>


        </div>
    );
};

export default Home;
